# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Restore dependencies
COPY WebConnection/WebConnection.csproj WebConnection/
COPY DataAccess/DataAccess.csproj DataAccess/
COPY Services/Services.csproj Services/
COPY Entities/Entities.csproj Entities/
RUN dotnet restore WebConnection/WebConnection.csproj
# Copy the rest of the source code
WORKDIR /src/SimpleApi
COPY . .
# Publish the application
RUN dotnet build WebConnection/WebConnection.csproj -c Release -o /app/build

# Final stage
RUN dotnet publish WebConnection/WebConnection.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

# Copy necessary files from the build stage
COPY --from=build /app/build .

# Expose port 7139 for the API
EXPOSE 7139

# Start the Web API
ENTRYPOINT ["dotnet", "WebConnection.dll"]